// Generated by scripts/generate-resume-translations.mjs.
// Proper names, official publication titles, URLs, and technology names remain in the source data.

export const generatedResumeTranslations = {
  "no": {
    "banner": [
      "Master i datavitenskap og forsker innen anvendt KI, med utvikling av intelligente systemer for multivariat tidsserieanalyse, anomalideteksjon, gjenfinningsforsterket generering og datasyn.",
      "Jeg kombinerer grundig forskning innen maskinlæring med produksjonsrettet utvikling og omsetter nye ideer til skalerbare, forklarbare løsninger på reelle vitenskapelige og industrielle utfordringer."
    ],
    "researchInterests": [
      "Maskinlæring",
      "Forklarlig AI",
      "Uovervåket anomalideteksjon",
      "Retrieval-Augmented Generation (RAG)",
      "Anvendt datasyn",
      "Kantslutning"
    ],
    "skillLabels": [
      "Deep Learning & AI",
      "Språk og backend",
      "Infrastruktur og sky",
      "Datavisualisering og verktøy",
      "Talte språk"
    ],
    "spokenLanguages": [
      "Engelsk — C1 / Flytende",
      "Tysk — B1/B2 / Middels",
      "Bengali - innfødt",
      "Norsk — Grunnleggende"
    ],
    "experiences": [
      {
        "role": "Dataforsker (arbeidsstudent)",
        "location": "Erlangen, Tyskland",
        "duration": "oktober 2025 – mars 2026",
        "bullets": [
          "Utviklet en ende-til-ende Python-mikrotjeneste for å hente hendelser fra en ekstern API og publisere dem til Azure Event Hub som en del av et proof of concept.",
          "Aktivert Multi-Agent System-integrasjon med EcoMAIN-plattformen, i samarbeid med Alexander Thamm om avansert avviksdeteksjon.",
          "Opprettholdt og feilsøkte Vue.js frontend-applikasjoner, optimaliserte backend API-kall og tilpasset brukergrensesnittkomponenter med komplekse tekniske krav."
        ]
      },
      {
        "role": "Dataanalytiker (arbeidende student)",
        "location": "Erlangen, Tyskland",
        "duration": "desember 2024 – september 2025",
        "bullets": [
          "Administrerte komplekse relasjonsdatabaser (MS SQL, MySQL) i den operative R&D-divisjonen, og skrev optimaliserte spørringer for omfattende datamigrasjoner.",
          "Designet og implementert automatiserte ETL/ELT-dataflyter, synkroniserte data fra SharePoint og Excel til SQL ved hjelp av Power Automate og Alteryx.",
          "Arkitekterte en ny samarbeidende backend-database for portefølje- og utviklingsdata for å støtte digitale brukssaker."
        ]
      },
      {
        "role": "Dataanalytiker",
        "location": "Fjernarbeid",
        "duration": "oktober 2021 – mars 2023",
        "bullets": [
          "Utført komplekse ETL-prosesser ved å koble Snowflake, MySQL og Excel for å trekke ut og transformere store datasett ved hjelp av Power Query.",
          "Bygget interaktive analytiske dashboards for å gi handlingskraftig, datadrevet innsikt til utøvende interessenter.",
          "Brukte smidige metoder (Kanban, Scrum) for å kartlegge interessentkrav og effektivisere prosjektleveransen."
        ]
      }
    ],
    "education": [
      {
        "degree": "Master of Science i datavitenskap",
        "location": "Erlangen, Tyskland",
        "duration": "oktober 2022 – juni 2026",
        "thesisTitle": "Anomalideteksjonsagent for tidsseriedata (Prosessindustri) som kan integreres i et Multi Agent System",
        "bullets": [
          "Arkitekterte en uovervåket maskinlæringspipeline for å oppdage anomalier i komplekse, multivariate tidsseriedata for prosessindustrien.",
          "Designet systemet som en uavhengig, skalerbar agent for sømløs integrasjon i et større industrielt Multi-Agent System-økosystem, ferdigstilt i samarbeid med Siemens Energy."
        ]
      },
      {
        "degree": "Bachelor i teknologi i informatikk og ingeniørfag",
        "location": "Kolkata, India",
        "duration": "juli 2017 – mai 2021",
        "thesisTitle": "Design og evaluering av et lett system for ansiktsuttrykksgjenkjenning i sanntid",
        "bullets": [
          "Konstruerte en tilpasset, svært effektiv Mini-Xception CNN (56 951 parametere) fra bunnen av ved å bruke PyTorch for å klassifisere syv grunnleggende følelser.",
          "Reduserte alvorlig klasseubalanse i FERPlus-datasettet ved å bruke en optimert vektingstrategi med kvadratrot invers frekvenstap, og oppnådde 75,40 % testnøyaktighet.",
          "Distribuerte modellen for sanntids kantslutning ved bruk av MediaPipe BlazeFace, og opprettholdt 30 FPS med ultralav latens (3,42 ms) på CPU-maskinvare."
        ]
      }
    ],
    "projects": [
      {
        "title": "SENSASJON: Navigasjonssystem for synshemmede",
        "context": "Master Seminar",
        "bullets": [
          "Designet et assisterende navigasjonssystem som smelter sammen DeepLabv3+ ResNet50 semantisk segmentering med Valhalla GPS-ruting for sanntids fortauveiledning.",
          "Finjusterte modellen på Mapillary-datasettet og eksporterte den til ONNX via TorchScript for effektiv CPU/GPU-inferens på live kamerastrømmer.",
          "Utviklet en romlig analysealgoritme for å gi retningskommandoer basert på dominerende fortauspikselfordeling."
        ]
      },
      {
        "title": "Driver's Freund: AI Multilingual Chatbot",
        "context": "2025 – i dag",
        "bullets": [
          "Arkitekterte en fullstack tysk chatbot for kjørelover ved å bruke en Retrieval-Augmented Generation-pipeline (MiniLM + Chroma + Perplexity).",
          "Implementerte en tospråklig NLP-pipeline (EN/DE) ved bruk av spaCy for klassifisering og generering, distribuert på en VPS med Docker og CI/CD-automatisering."
        ]
      },
      {
        "title": "Chicago kriminalitetsdataanalyse",
        "context": "2024 – 2025",
        "bullets": [
          "Bygget en ende-til-ende ETL-rørledning som korrelerer Chicago-kriminalitetshendelser med meteorologiske data fra Chicago Police Department og vær-APIer.",
          "Implementerte automatisert testing og CI/CD-pipelines via GitHub Actions for å sikre full reproduserbarhet av datateknologiens livssyklus."
        ]
      }
    ],
    "publicationStatuses": [
      "Sendt · Under vurdering",
      "Sendt · Fortrykk venter på Research Square"
    ]
  },
  "fi": {
    "banner": [
      "Data Science -maisteri ja soveltavan tekoälyn tutkija, joka kehittää älykkäitä järjestelmiä monimuuttujaiseen aikasarja-analyysiin, poikkeamien tunnistukseen, RAG-ratkaisuihin ja konenäköön.",
      "Yhdistän perusteellisen koneoppimistutkimuksen tuotantotason ohjelmistokehitykseen ja muunnan uudet ideat skaalautuviksi, selitettäviksi ratkaisuiksi todellisiin tieteellisiin ja teollisiin haasteisiin."
    ],
    "researchInterests": [
      "Koneoppiminen",
      "Selitettävä AI",
      "Valvomaton poikkeamien tunnistus",
      "Retrieval-Augmented Generation (RAG)",
      "Sovellettu tietokonenäkö",
      "Reunapäättely"
    ],
    "skillLabels": [
      "Syväoppiminen ja tekoäly",
      "Kielet ja taustaohjelma",
      "Infrastruktuuri ja pilvi",
      "Tietojen visualisointi ja työkalut",
      "Puhutut kielet"
    ],
    "spokenLanguages": [
      "Englanti — C1 / Sujuva",
      "saksa — B1/B2 / Keskitaso",
      "Bengali - syntyperäinen",
      "Norja - Perus"
    ],
    "experiences": [
      {
        "role": "Data Scientist (työskentelyopiskelija)",
        "location": "Erlangen, Saksa",
        "duration": "Lokakuu 2025 – maaliskuu 2026",
        "bullets": [
          "Kehitetty kattava Python-mikropalvelu, joka noutaa tapahtumia ulkoisesta API:sta ja julkaisee ne Azure Event Hubiin osana konseptitodistusta.",
          "Otettu käyttöön Multi-Agent System -integraatio EcoMAIN-alustan kanssa, yhteistyössä Alexander Thammin kanssa edistyneessä poikkeamien havaitsemisessa.",
          "Ylläpidetty ja virheenkorjattu Vue.js-käyttöliittymäsovelluksia, optimoida tausta-API-kutsut ja sovitettu käyttöliittymäkomponentit monimutkaisiin teknisiin vaatimuksiin."
        ]
      },
      {
        "role": "Dataanalyytikko (työskentelyopiskelija)",
        "location": "Erlangen, Saksa",
        "duration": "Joulukuu 2024 – syyskuu 2025",
        "bullets": [
          "Hallinnoi monimutkaisia relaatiotietokantoja (MS SQL, MySQL) operatiivisessa T&K-divisioonassa ja kirjoittaa optimoituja kyselyitä laajoja tiedonsiirtoja varten.",
          "Suunniteltu ja toteutettu automatisoidut ETL/ELT-tietovirrat, tietojen synkronointi SharePointista ja Excelistä SQL:ään Power Automaten ja Alteryxin avulla.",
          "Suunnitteli uuden yhteistyöpohjaisen taustatietokannan portfolio- ja kehitystiedoille tukemaan digitaalisia käyttötapauksia."
        ]
      },
      {
        "role": "Data-analyytikko",
        "location": "Etätyö",
        "duration": "Lokakuu 2021 – maaliskuu 2023",
        "bullets": [
          "Suoritti monimutkaisia ETL-prosesseja yhdistämällä Snowflaken, MySQL:n ja Excelin suuren mittakaavan tietojoukkojen purkamiseksi ja muuntamiseksi Power Queryn avulla.",
          "Rakennetut interaktiiviset analyyttiset hallintapaneelit tarjoavat toimivia, tietoihin perustuvia oivalluksia johtaville sidosryhmille.",
          "Käytettiin ketteriä menetelmiä (Kanban, Scrum) sidosryhmien vaatimusten kartoittamiseen ja projektin toimituksen tehostamiseen."
        ]
      }
    ],
    "education": [
      {
        "degree": "Tietotekniikan maisteri",
        "location": "Erlangen, Saksa",
        "duration": "Lokakuu 2022 – Kesäkuu 2026",
        "thesisTitle": "Poikkeamien havaitsemisagentti aikasarjatiedoille (prosessiteollisuus), joka voidaan integroida Multi Agent -järjestelmään",
        "bullets": [
          "Suunnitteli valvomattoman koneoppimisputkiston havaitsemaan poikkeavuuksia monimutkaisissa, monimuuttujaisissa aikasarjatiedoissa prosessiteollisuudelle.",
          "Suunniteltu järjestelmä itsenäiseksi, skaalautuvaksi agentiksi, joka mahdollistaa saumattoman integroinnin laajempaan teolliseen Multi-Agent System -ekosysteemiin, joka valmistettiin yhteistyössä Siemens Energyn kanssa."
        ]
      },
      {
        "degree": "Tietojenkäsittelytieteen ja tekniikan kandidaatti",
        "location": "Kolkata, Intia",
        "duration": "Heinäkuu 2017 – toukokuu 2021",
        "thesisTitle": "Kevyen reaaliaikaisen ilmeentunnistusjärjestelmän suunnittelu ja arviointi",
        "bullets": [
          "Suunnitteli mukautetun, erittäin tehokkaan Mini-Xception CNN:n (56 951 parametria) alusta alkaen käyttämällä PyTorchia seitsemän perustunteen luokitteluun.",
          "Vähensi vakavaa luokkaepätasapainoa FERPlus-tietojoukossa käyttämällä optimoitua neliöjuuren käänteistaajuushäviön painotusstrategiaa, jolloin saavutettiin 75,40 %:n testitarkkuus.",
          "Oti mallin käyttöön reaaliaikaiseen reunapäätelmään MediaPipe BlazeFacella, ylläpitäen 30 FPS:n nopeutta erittäin alhaisella latenssilla (3,42 ms) suoritinlaitteistossa."
        ]
      }
    ],
    "projects": [
      {
        "title": "SENSATION: Navigointijärjestelmä näkövammaisille",
        "context": "Mestariseminaari",
        "bullets": [
          "Suunniteltu avustava navigointijärjestelmä, joka yhdistää DeepLabv3+ ResNet50:n semanttisen segmentoinnin Valhalla GPS-reitityksen kanssa reaaliaikaista jalkakäytäväopastusta varten.",
          "Hienosääti mallia Mapillary-tietojoukossa ja vieti sen ONNX:hen TorchScriptin kautta tehokkaan CPU/GPU-päätelmän tekemiseksi reaaliaikaisista kameravirroista.",
          "Suunnitteli tila-analyysialgoritmin antamaan suuntakäskyjä, jotka perustuvat hallitsevaan jalkakäytävän pikselijakaumaan."
        ]
      },
      {
        "title": "Driver's Freund: AI Multilingual Chatbot",
        "context": "2025 – nykyhetki",
        "bullets": [
          "Suunnitteli täyden pinon saksalaisen ajolain chatbotin käyttämällä Retrieval-Augmented Generation -piippua (MiniLM + Chroma + Perplexity).",
          "Otettiin käyttöön kaksikielinen NLP-putki (EN/DE) käyttämällä spaCy:tä luokitteluun ja luomiseen, otettu käyttöön VPS:ssä, jossa on Docker ja CI/CD-automaatio."
        ]
      },
      {
        "title": "Chicagon rikostietojen analyysi",
        "context": "2024-2025",
        "bullets": [
          "Rakensi päästä päähän ETL-putkilinjan, joka korreloi Chicagon rikostapaukset Chicagon poliisilaitoksen ja sääsovellusliittymien säätietojen kanssa.",
          "Otettiin käyttöön automaattinen testaus ja CI/CD-putkistot GitHub Actionsin kautta varmistaakseen tietotekniikan elinkaaren täyden toistettavuuden."
        ]
      }
    ],
    "publicationStatuses": [
      "Lähetetty · Tarkistuksessa",
      "Lähetetty · Preprint vireillä Research Squarella"
    ]
  },
  "sv": {
    "banner": [
      "Masterutbildad inom datavetenskap och forskare inom tillämpad AI, med fokus på intelligenta system för multivariat tidsserieanalys, anomalidetektering, RAG och datorseende.",
      "Jag förenar gedigen forskning inom maskininlärning med produktionsnära utveckling och omsätter nya idéer i skalbara, förklarbara lösningar på verkliga vetenskapliga och industriella utmaningar."
    ],
    "researchInterests": [
      "Maskininlärning",
      "Förklarlig AI",
      "Oövervakad anomalidetektering",
      "Retrieval-Augmented Generation (RAG)",
      "Tillämpad datorseende",
      "Edge Inferens"
    ],
    "skillLabels": [
      "Deep Learning & AI",
      "Språk & Backend",
      "Infrastruktur och moln",
      "Datavisualisering och verktyg",
      "Talade språk"
    ],
    "spokenLanguages": [
      "Engelska — C1 / Flytande",
      "Tyska — B1/B2 / Mellanliggande",
      "Bengali - infödd",
      "Norska — Grundläggande"
    ],
    "experiences": [
      {
        "role": "Dataforskare (arbetande student)",
        "location": "Erlangen, Tyskland",
        "duration": "oktober 2025 – mars 2026",
        "bullets": [
          "Utvecklade en heltäckande Python-mikrotjänst för att hämta händelser från ett externt API och publicera dem till Azure Event Hub som en del av ett proof of concept.",
          "Aktiverade Multi-Agent System-integration med EcoMAIN-plattformen, i samarbete med Alexander Thamm om avancerad anomalidetektering.",
          "Underhöll och felsökte Vue.js frontend-applikationer, optimerade backend API-anrop och anpassade UI-komponenter med komplexa tekniska krav."
        ]
      },
      {
        "role": "Dataanalytiker (arbetande student)",
        "location": "Erlangen, Tyskland",
        "duration": "Dec 2024 – september 2025",
        "bullets": [
          "Hanterade komplexa relationsdatabaser (MS SQL, MySQL) i den operativa R&D-divisionen, skrev optimerade frågor för omfattande datamigreringar.",
          "Designade och implementerade automatiserade ETL/ELT-dataflöden, synkroniserade data från SharePoint och Excel till SQL med Power Automate och Alteryx.",
          "Byggde en ny samarbetande backend-databas för portfölj- och utvecklingsdata för att stödja digitala användningsfall."
        ]
      },
      {
        "role": "Dataanalytiker",
        "location": "Distansarbete",
        "duration": "oktober 2021 – mars 2023",
        "bullets": [
          "Exekverade komplexa ETL-processer genom att koppla Snowflake, MySQL och Excel för att extrahera och transformera storskaliga datamängder med Power Query.",
          "Byggt interaktiva analytiska instrumentpaneler för att ge handlingskraftiga, datadrivna insikter till verkställande intressenter.",
          "Använde agila metoder (Kanban, Scrum) för att kartlägga intressenters krav och effektivisera projektleverans."
        ]
      }
    ],
    "education": [
      {
        "degree": "Civilingenjör i datavetenskap",
        "location": "Erlangen, Tyskland",
        "duration": "oktober 2022 – juni 2026",
        "thesisTitle": "Anomalidetekteringsagent för tidsseriedata (Process Industry) som kan integreras i ett Multi Agent System",
        "bullets": [
          "Byggde en oövervakad pipeline för maskininlärning för att upptäcka anomalier i komplexa, multivariata tidsseriedata för processindustrin.",
          "Designade systemet som en oberoende, skalbar agent för sömlös integration i ett större industriellt Multi-Agent System-ekosystem, färdigställt i samarbete med Siemens Energy."
        ]
      },
      {
        "degree": "Kandidatexamen i datavetenskap och teknik",
        "location": "Kolkata, Indien",
        "duration": "juli 2017 – maj 2021",
        "thesisTitle": "Design och utvärdering av ett lättviktssystem för ansiktsuttryck i realtid",
        "bullets": [
          "Konstruerade en anpassad, högeffektiv Mini-Xception CNN (56 951 parametrar) från grunden med PyTorch för att klassificera sju grundläggande känslor.",
          "Minskade allvarlig klassobalans i FERPlus-datauppsättningen med hjälp av en optimerad viktningsstrategi för inverterad frekvensförlust med kvadratrot, vilket uppnådde 75,40 % testnoggrannhet.",
          "Implementerade modellen för kantslutning i realtid med MediaPipe BlazeFace, upprätthöll 30 FPS med ultralåg latens (3,42 ms) på CPU-hårdvara."
        ]
      }
    ],
    "projects": [
      {
        "title": "SENSATION: Navigationssystem för synskadade",
        "context": "Masterseminarium",
        "bullets": [
          "Designade ett assisterande navigationssystem som sammansmälter DeepLabv3+ ResNet50 semantisk segmentering med Valhalla GPS-routing för vägledning i realtid.",
          "Finjusterade modellen på Mapillary-datauppsättningen och exporterade den till ONNX via TorchScript för effektiv CPU/GPU-inferens på livekameraströmmar.",
          "Konstruerade en rumslig analysalgoritm för att utfärda riktningskommandon baserat på dominerande trottoarpixelfördelning."
        ]
      },
      {
        "title": "Driver's Freund: AI Multilingual Chatbot",
        "context": "2025 – nu",
        "bullets": [
          "Byggde en full-stack tysk körlagschattbot med hjälp av en Retrieval-Augmented Generation-pipeline (MiniLM + Chroma + Perplexity).",
          "Implementerade en tvåspråkig NLP-pipeline (EN/DE) med spaCy för klassificering och generering, utplacerad på en VPS med Docker och CI/CD-automatisering."
        ]
      },
      {
        "title": "Chicago brottsdataanalys",
        "context": "2024 – 2025",
        "bullets": [
          "Byggde en heltäckande ETL-pipeline som korrelerar Chicago brottsincidenter med meteorologiska data från Chicago Police Department och väder-API:er.",
          "Utplacerade automatisk testning och CI/CD-pipelines via GitHub Actions för att säkerställa full reproducerbarhet av datateknikens livscykel."
        ]
      }
    ],
    "publicationStatuses": [
      "Inskickad · Under granskning",
      "Inskickad · Förtryck väntar på Research Square"
    ]
  },
  "da": {
    "banner": [
      "Kandidat med en master i Data Science og forsker i anvendt AI med fokus på intelligente systemer til multivariat tidsserieanalyse, anomalidetektion, RAG og computersyn.",
      "Jeg kombinerer grundig forskning i maskinlæring med produktionsorienteret udvikling og omsætter nye idéer til skalerbare, forklarlige løsninger på virkelige videnskabelige og industrielle udfordringer."
    ],
    "researchInterests": [
      "Machine Learning",
      "Forklarlig AI",
      "Detektion af uovervåget anomali",
      "Retrieval-Augmented Generation (RAG)",
      "Anvendt computersyn",
      "Kantslutning"
    ],
    "skillLabels": [
      "Deep Learning & AI",
      "Sprog & Backend",
      "Infrastruktur & Cloud",
      "Datavisualisering og værktøjer",
      "Talte sprog"
    ],
    "spokenLanguages": [
      "Engelsk — C1 / Flydende",
      "Tysk — B1/B2 / Mellemliggende",
      "Bengali - indfødt",
      "Norsk — Grundlæggende"
    ],
    "experiences": [
      {
        "role": "Data Scientist (Working Student)",
        "location": "Erlangen, Tyskland",
        "duration": "oktober 2025 – marts 2026",
        "bullets": [
          "Udviklede en end-to-end Python-mikrotjeneste til at hente hændelser fra en ekstern API og udgive dem til Azure Event Hub som en del af et proof of concept.",
          "Aktiverede Multi-Agent System-integration med EcoMAIN-platformen, i samarbejde med Alexander Thamm om avanceret anomalidetektion.",
          "Vedligeholdt og fejlede Vue.js frontend-applikationer, optimerede backend API-kald og tilpassede UI-komponenter med komplekse tekniske krav."
        ]
      },
      {
        "role": "Dataanalytiker (arbejdende studerende)",
        "location": "Erlangen, Tyskland",
        "duration": "Dec. 2024 – Sep. 2025",
        "bullets": [
          "Administrerede komplekse relationelle databaser (MS SQL, MySQL) i den operationelle R&D division, skrev optimerede forespørgsler til omfattende datamigreringer.",
          "Designede og implementerede automatiserede ETL/ELT-datastrømme, synkroniserede data fra SharePoint og Excel til SQL ved hjælp af Power Automate og Alteryx.",
          "Arkitekterede en ny kollaborativ backend-database for portefølje- og udviklingsdata for at understøtte digitale use cases."
        ]
      },
      {
        "role": "Dataanalytiker",
        "location": "Fjernarbejde",
        "duration": "oktober 2021 – marts 2023",
        "bullets": [
          "Udført komplekse ETL-processer ved at forbinde Snowflake, MySQL og Excel for at udtrække og transformere store datasæt ved hjælp af Power Query.",
          "Bygget interaktive analytiske dashboards for at give handlingsorienterede, datadrevne indsigter til udøvende interessenter.",
          "Brugte agile metoder (Kanban, Scrum) til at kortlægge interessentkrav og strømline projektleverance."
        ]
      }
    ],
    "education": [
      {
        "degree": "Master of Science i datavidenskab",
        "location": "Erlangen, Tyskland",
        "duration": "oktober 2022 – juni 2026",
        "thesisTitle": "Anomali detektion Agent for tidsseriedata (Process Industry), der kan integreres i et Multi Agent System",
        "bullets": [
          "Arkitekterede en uovervåget maskinlæringspipeline for at detektere anomalier i komplekse, multivariate tidsseriedata til procesindustrien.",
          "Designet systemet som en uafhængig, skalerbar agent til problemfri integration i et større industrielt Multi-Agent System-økosystem, afsluttet i samarbejde med Siemens Energy."
        ]
      },
      {
        "degree": "Bachelor i teknologi i datalogi og teknik",
        "location": "Kolkata, Indien",
        "duration": "juli 2017 – maj 2021",
        "thesisTitle": "Design og evaluering af et letvægtssystem til ansigtsudtryksgenkendelse i realtid",
        "bullets": [
          "Konstrueret en brugerdefineret, højeffektiv Mini-Xception CNN (56.951 parametre) fra bunden ved hjælp af PyTorch til at klassificere syv grundlæggende følelser.",
          "Afbød alvorlig klasseubalance i FERPlus-datasættet ved hjælp af en optimeret vægtningsstrategi med kvadratrod omvendt frekvenstab, der opnåede 75,40 % testnøjagtighed.",
          "Implementerede modellen til kantslutning i realtid ved hjælp af MediaPipe BlazeFace, der opretholder 30 FPS med ultralav latency (3,42 ms) på CPU-hardware."
        ]
      }
    ],
    "projects": [
      {
        "title": "SENSATION: Navigationssystem for synshandicappede",
        "context": "Master Seminar",
        "bullets": [
          "Designet et assisterende navigationssystem, der fusionerer DeepLabv3+ ResNet50 semantisk segmentering med Valhalla GPS-routing til fortovsvejledning i realtid.",
          "Finjusterede modellen på Mapillary-datasættet og eksporterede den til ONNX via TorchScript for effektiv CPU/GPU-inferens på live kamerastreams.",
          "Konstrueret en rumlig analysealgoritme til at udstede retningsbestemte kommandoer baseret på dominerende fortovspixelfordeling."
        ]
      },
      {
        "title": "Driver's Freund: AI Multilingual Chatbot",
        "context": "2025 – i dag",
        "bullets": [
          "Arkitekterede en full-stack tysk kørselslovchatbot ved hjælp af en Retrieval-Augmented Generation-pipeline (MiniLM + Chroma + Perplexity).",
          "Implementerede en tosproget NLP-pipeline (EN/DE) ved hjælp af spaCy til klassificering og generering, implementeret på en VPS med Docker og CI/CD-automatisering."
        ]
      },
      {
        "title": "Chicago kriminalitetsdataanalyse",
        "context": "2024 – 2025",
        "bullets": [
          "Byggede en ende-til-ende ETL-pipeline, der korrelerer Chicago-kriminalitetshændelser med meteorologiske data fra Chicago Police Department og vejr-API'er.",
          "Implementeret automatiseret test og CI/CD-pipelines via GitHub Actions for at sikre fuld reproducerbarhed af datateknologiens livscyklus."
        ]
      }
    ],
    "publicationStatuses": [
      "Indsendt · Under gennemgang",
      "Indsendt · Fortryk afventer på Research Square"
    ]
  },
  "it": {
    "banner": [
      "Laureato magistrale in Data Science e ricercatore nell’intelligenza artificiale applicata, sviluppo sistemi intelligenti per l’analisi di serie temporali multivariate, il rilevamento di anomalie, la RAG e la visione artificiale.",
      "Unisco una rigorosa ricerca nel machine learning all’ingegneria orientata alla produzione, trasformando idee innovative in soluzioni scalabili e spiegabili per sfide scientifiche e industriali reali."
    ],
    "researchInterests": [
      "Apprendimento automatico",
      "IA spiegabile",
      "Rilevamento anomalie non supervisionato",
      "Generazione aumentata di recupero (RAG)",
      "Visione artificiale applicata",
      "Inferenza sui bordi"
    ],
    "skillLabels": [
      "Apprendimento profondo e intelligenza artificiale",
      "Lingue e backend",
      "Infrastruttura e cloud",
      "Visualizzazione e strumenti dei dati",
      "Lingue parlate"
    ],
    "spokenLanguages": [
      "Inglese — C1/Fluente",
      "Tedesco — B1/B2 / Intermedio",
      "Bengalese: nativo",
      "Norvegese: base"
    ],
    "experiences": [
      {
        "role": "Scienziato dei dati (studente lavoratore)",
        "location": "Erlangen, Germania",
        "duration": "Ottobre 2025 – marzo 2026",
        "bullets": [
          "Sviluppato un microservizio Python end-to-end per recuperare eventi da un'API esterna e pubblicarli nell'Hub eventi di Azure come parte di una prova di concetto.",
          "Abilitazione dell'integrazione del sistema multi-agente con la piattaforma EcoMAIN, collaborazione con Alexander Thamm sul rilevamento avanzato delle anomalie.",
          "Mantenimento e debug delle applicazioni frontend Vue.js, ottimizzazione delle chiamate API backend e allineamento dei componenti dell'interfaccia utente con requisiti tecnici complessi."
        ]
      },
      {
        "role": "Analista di dati (studente lavoratore)",
        "location": "Erlangen, Germania",
        "duration": "Dicembre 2024 – settembre 2025",
        "bullets": [
          "Gestito database relazionali complessi (MS SQL, MySQL) nella divisione operativa di ricerca e sviluppo, scrivendo query ottimizzate per estese migrazioni di dati.",
          "Progettato e implementato flussi di dati ETL/ELT automatizzati, sincronizzando i dati da SharePoint ed Excel a SQL utilizzando Power Automate e Alteryx.",
          "Ho progettato un nuovo database backend collaborativo per i dati di portfolio e sviluppo per supportare i casi d'uso digitali."
        ]
      },
      {
        "role": "Analista di dati",
        "location": "Da remoto",
        "duration": "Ottobre 2021 – marzo 2023",
        "bullets": [
          "Eseguiti processi ETL complessi collegando Snowflake, MySQL ed Excel per estrarre e trasformare set di dati su larga scala utilizzando Power Query.",
          "Costruito dashboard analitici interattivi per fornire approfondimenti fruibili e basati sui dati alle parti interessate esecutive.",
          "Utilizzo di metodologie agili (Kanban, Scrum) per mappare i requisiti delle parti interessate e semplificare la consegna dei progetti."
        ]
      }
    ],
    "education": [
      {
        "degree": "Master in scienza dei dati",
        "location": "Erlangen, Germania",
        "duration": "Ottobre 2022 – giugno 2026",
        "thesisTitle": "Agente di rilevamento anomalie per dati di serie temporali (Industria di processo) che può essere integrato in un sistema multi-agente",
        "bullets": [
          "Ho progettato una pipeline di machine learning non supervisionata per rilevare anomalie in dati di serie temporali complessi e multivariati per l'industria di processo.",
          "Progettato il sistema come agente indipendente e scalabile per un'integrazione perfetta in un ecosistema di sistemi multi-agente industriale più ampio, completato in collaborazione con Siemens Energy."
        ]
      },
      {
        "degree": "Laurea in Tecnologia in Informatica e Ingegneria",
        "location": "Calcutta, India",
        "duration": "Lug. 2017 – maggio 2021",
        "thesisTitle": "Progettazione e valutazione di un sistema leggero di riconoscimento delle espressioni facciali in tempo reale",
        "bullets": [
          "Progettato da zero una Mini-Xception CNN personalizzata ed altamente efficiente (56.951 parametri) utilizzando PyTorch per classificare sette emozioni di base.",
          "Mitigato grave squilibrio di classe nel set di dati FERPlus utilizzando una strategia di ponderazione della perdita di frequenza inversa con radice quadrata ottimizzata, ottenendo una precisione del test del 75,40%.",
          "Distribuito il modello per l'inferenza edge in tempo reale utilizzando MediaPipe BlazeFace, sostenendo 30 FPS con latenza ultra bassa (3,42 ms) sull'hardware della CPU."
        ]
      }
    ],
    "projects": [
      {
        "title": "SENSATION: sistema di navigazione per non vedenti",
        "context": "Seminario Magistrale",
        "bullets": [
          "Progettato un sistema di navigazione assistiva che fonde la segmentazione semantica DeepLabv3+ ResNet50 con il routing GPS Valhalla per la guida sui marciapiedi in tempo reale.",
          "Perfezionato il modello sul set di dati Mapillary e esportato su ONNX tramite TorchScript per un'efficiente inferenza CPU/GPU sui flussi di telecamere live.",
          "Progettato un algoritmo di analisi spaziale per emettere comandi direzionali basati sulla distribuzione dominante dei pixel sul marciapiede."
        ]
      },
      {
        "title": "Amico dell'autista: chatbot multilingue AI",
        "context": "2025 – Presente",
        "bullets": [
          "Ho progettato un chatbot completo per il diritto di guida tedesco utilizzando una pipeline di generazione aumentata di recupero (MiniLM + Chroma + Perplexity).",
          "Implementata una pipeline NLP bilingue (EN/DE) utilizzando spaCy per la classificazione e la generazione, distribuita su un VPS con Docker e automazione CI/CD."
        ]
      },
      {
        "title": "Analisi dei dati sulla criminalità di Chicago",
        "context": "2024 – 2025",
        "bullets": [
          "Costruito una pipeline ETL end-to-end che correla gli incidenti criminali di Chicago con i dati meteorologici del dipartimento di polizia di Chicago e le API meteorologiche.",
          "Implementazione di test automatizzati e pipeline CI/CD tramite GitHub Actions per garantire la completa riproducibilità del ciclo di vita dell'ingegneria dei dati."
        ]
      }
    ],
    "publicationStatuses": [
      "Inserito · In fase di revisione",
      "Inserito · Prestampa in attesa su Research Square"
    ]
  },
  "nl": {
    "banner": [
      "Afgestudeerd master in Data Science en onderzoeker in toegepaste AI, gericht op intelligente systemen voor multivariate tijdreeksanalyse, anomaliedetectie, RAG en computer vision.",
      "Ik combineer grondig onderzoek naar machine learning met productiegerichte engineering en vertaal nieuwe ideeën naar schaalbare, uitlegbare oplossingen voor wetenschappelijke en industriële uitdagingen uit de praktijk."
    ],
    "researchInterests": [
      "Machinaal leren",
      "Verklaarbare AI",
      "Ongecontroleerde detectie van afwijkingen",
      "Retrieval-augmented generatie (RAG)",
      "Toegepaste computervisie",
      "Randinferentie"
    ],
    "skillLabels": [
      "Diep leren en AI",
      "Talen en backend",
      "Infrastructuur en cloud",
      "Datavisualisatie en hulpmiddelen",
      "Gesproken talen"
    ],
    "spokenLanguages": [
      "Engels — C1 / Vloeiend",
      "Duits — B1/B2 / Gemiddeld",
      "Bengaals — Inheems",
      "Noors — Basis"
    ],
    "experiences": [
      {
        "role": "Data Scientist (Werkstudent)",
        "location": "Erlangen, Duitsland",
        "duration": "Oktober 2025 – maart 2026",
        "bullets": [
          "Een end-to-end Python-microservice ontwikkeld om gebeurtenissen op te halen uit een externe API en deze te publiceren naar Azure Event Hub als onderdeel van een proof of concept.",
          "Multi-Agent systeemintegratie met het EcoMAIN-platform mogelijk gemaakt, in samenwerking met Alexander Thamm aan geavanceerde anomaliedetectie.",
          "Onderhouden en debuggen van Vue.js frontend-applicaties, optimaliseren van backend API-aanroepen en afstemmen van UI-componenten met complexe technische vereisten."
        ]
      },
      {
        "role": "Data Analist (Werkstudent)",
        "location": "Erlangen, Duitsland",
        "duration": "december 2024 – september 2025",
        "bullets": [
          "Beheerde complexe relationele databases (MS SQL, MySQL) in de operationele R&D-afdeling en schreef geoptimaliseerde queries voor uitgebreide datamigraties.",
          "Ontwerp en implementatie van geautomatiseerde ETL/ELT-gegevensstromen, waarbij gegevens van SharePoint en Excel naar SQL worden gesynchroniseerd met behulp van Power Automate en Alteryx.",
          "Een nieuwe collaboratieve backend-database ontworpen voor portfolio- en ontwikkelingsgegevens ter ondersteuning van digitale gebruiksscenario's."
        ]
      },
      {
        "role": "Data-analist",
        "location": "Op afstand",
        "duration": "Oktober 2021 – maart 2023",
        "bullets": [
          "Voerde complexe ETL-processen uit door Snowflake, MySQL en Excel te verbinden om grootschalige datasets te extraheren en te transformeren met behulp van Power Query.",
          "Bouwde interactieve analytische dashboards om bruikbare, datagestuurde inzichten te bieden aan uitvoerende belanghebbenden.",
          "Gebruikte agile methodologieën (Kanban, Scrum) om de vereisten van belanghebbenden in kaart te brengen en de projectoplevering te stroomlijnen."
        ]
      }
    ],
    "education": [
      {
        "degree": "Master of Science in Datawetenschap",
        "location": "Erlangen, Duitsland",
        "duration": "Oktober 2022 – juni 2026",
        "thesisTitle": "Anomaliedetectie Agent voor tijdreeksgegevens (procesindustrie) die kunnen worden geïntegreerd in een Multi Agent-systeem",
        "bullets": [
          "Een machine learning-pijplijn zonder toezicht ontworpen om afwijkingen in complexe, multivariate tijdreeksgegevens voor de procesindustrie te detecteren.",
          "Ontwierp het systeem als een onafhankelijke, schaalbare agent voor naadloze integratie in een groter industrieel Multi-Agent Systeem-ecosysteem, voltooid in samenwerking met Siemens Energy."
        ]
      },
      {
        "degree": "Bachelor in de technologie in computerwetenschappen en techniek",
        "location": "Calcutta, India",
        "duration": "juli 2017 – mei 2021",
        "thesisTitle": "Ontwerp en evaluatie van een lichtgewicht realtime gezichtsuitdrukkingsherkenningssysteem",
        "bullets": [
          "Met PyTorch een op maat gemaakte, zeer efficiënte Mini-Xception CNN (56.951 parameters) ontwikkeld om zeven basisemoties te classificeren.",
          "Ernstige klassenonbalans in de FERPlus-dataset verminderd met behulp van een geoptimaliseerde vierkantswortel-inverse-frequentie verlieswegingsstrategie, waardoor een testnauwkeurigheid van 75,40% werd bereikt.",
          "Implementeerde het model voor real-time edge-inferentie met behulp van MediaPipe BlazeFace, waarbij 30 FPS met ultralage latentie (3,42 ms) op CPU-hardware werd ondersteund."
        ]
      }
    ],
    "projects": [
      {
        "title": "SENSATION: navigatiesysteem voor visueel gehandicapten",
        "context": "Master Seminarie",
        "bullets": [
          "Een ondersteunend navigatiesysteem ontworpen dat de semantische segmentatie van DeepLabv3+ ResNet50 combineert met Valhalla GPS-routering voor realtime trottoirbegeleiding.",
          "Het model op de Mapillary-dataset verfijnd en via TorchScript naar ONNX geëxporteerd voor efficiënte CPU/GPU-inferentie bij live camerastreams.",
          "Een algoritme voor ruimtelijke analyse ontworpen om richtingsopdrachten te geven op basis van de dominante pixelverdeling op het trottoir."
        ]
      },
      {
        "title": "Chauffeursvriend: AI meertalige chatbot",
        "context": "2025 – heden",
        "bullets": [
          "Een full-stack chatbot voor Duits rijrecht ontworpen met behulp van een Retrieval-Augmented Generation-pijplijn (MiniLM + Chroma + Perplexity).",
          "Implementeerde een tweetalige NLP-pijplijn (EN/DE) met behulp van spaCy voor classificatie en generatie, geïmplementeerd op een VPS met Docker en CI/CD-automatisering."
        ]
      },
      {
        "title": "Analyse van misdaadgegevens uit Chicago",
        "context": "2024 – 2025",
        "bullets": [
          "Bouwde een end-to-end ETL-pijplijn die misdaadincidenten in Chicago correleerde met meteorologische gegevens van de Chicago Police Department en weer-API's.",
          "Geautomatiseerde tests en CI/CD-pijplijnen geïmplementeerd via GitHub Actions om volledige reproduceerbaarheid van de data-engineeringlevenscyclus te garanderen."
        ]
      }
    ],
    "publicationStatuses": [
      "Ingediend · Wordt beoordeeld",
      "Ingediend · Preprint in behandeling op Research Square"
    ]
  },
  "fr": {
    "banner": [
      "Diplômé d’un master en Data Science et chercheur en IA appliquée, je développe des systèmes intelligents pour l’analyse de séries temporelles multivariées, la détection d’anomalies, la RAG et la vision par ordinateur.",
      "J’allie une recherche rigoureuse en apprentissage automatique à une ingénierie orientée production afin de transformer des idées nouvelles en solutions évolutives et explicables pour des défis scientifiques et industriels concrets."
    ],
    "researchInterests": [
      "Apprentissage automatique",
      "IA explicable",
      "Détection d'anomalies non supervisée",
      "Génération augmentée par récupération (RAG)",
      "Vision par ordinateur appliquée",
      "Inférence de bord"
    ],
    "skillLabels": [
      "Apprentissage profond et IA",
      "Langues et back-end",
      "Infrastructures et Cloud",
      "Visualisation des données et outils",
      "Langues parlées"
    ],
    "spokenLanguages": [
      "Anglais — C1 / Courant",
      "Allemand — B1/B2 / Intermédiaire",
      "Bengali — Native",
      "Norvégien — Basique"
    ],
    "experiences": [
      {
        "role": "Data Scientist (étudiant en activité)",
        "location": "Erlangen, Allemagne",
        "duration": "Octobre 2025 – mars 2026",
        "bullets": [
          "Développement d'un microservice Python de bout en bout pour récupérer des événements à partir d'une API externe et les publier sur Azure Event Hub dans le cadre d'une preuve de concept.",
          "Intégration du système multi-agent avec la plateforme EcoMAIN, en collaboration avec Alexander Thamm sur la détection avancée des anomalies.",
          "Maintenir et déboguer les applications frontend Vue.js, en optimisant les appels d'API backend et en alignant les composants de l'interface utilisateur avec des exigences techniques complexes."
        ]
      },
      {
        "role": "Analyste de données (étudiant en activité)",
        "location": "Erlangen, Allemagne",
        "duration": "Déc. 2024 – septembre 2025",
        "bullets": [
          "Gestion de bases de données relationnelles complexes (MS SQL, MySQL) dans la division R&D opérationnelle, rédaction de requêtes optimisées pour des migrations de données étendues.",
          "Conception et mise en œuvre de flux de données ETL/ELT automatisés, synchronisant les données de SharePoint et Excel vers SQL à l'aide de Power Automate et Alteryx.",
          "Conception d'une nouvelle base de données back-end collaborative pour les données de portefeuille et de développement afin de prendre en charge les cas d'utilisation numérique."
        ]
      },
      {
        "role": "Analyste de données",
        "location": "À distance",
        "duration": "Octobre 2021 – mars 2023",
        "bullets": [
          "Exécution de processus ETL complexes en connectant Snowflake, MySQL et Excel pour extraire et transformer des ensembles de données à grande échelle à l'aide de Power Query.",
          "Création de tableaux de bord analytiques interactifs pour fournir des informations exploitables et basées sur des données aux parties prenantes dirigeantes.",
          "Utilisation de méthodologies agiles (Kanban, Scrum) pour cartographier les exigences des parties prenantes et rationaliser la livraison du projet."
        ]
      }
    ],
    "education": [
      {
        "degree": "Master of Science en science des données",
        "location": "Erlangen, Allemagne",
        "duration": "Octobre 2022 – juin 2026",
        "thesisTitle": "Agent de détection d'anomalies pour données de séries temporelles (Industrie de Process) pouvant être intégré dans un Système Multi Agent",
        "bullets": [
          "Conception d'un pipeline d'apprentissage automatique non supervisé pour détecter les anomalies dans des séries chronologiques complexes et multivariées pour l'industrie des procédés.",
          "Conçu le système comme un agent indépendant et évolutif pour une intégration transparente dans un écosystème de système multi-agent industriel plus vaste, réalisé en collaboration avec Siemens Energy."
        ]
      },
      {
        "degree": "Baccalauréat technologique en informatique et ingénierie",
        "location": "Calcutta, Inde",
        "duration": "Juillet 2017 – mai 2021",
        "thesisTitle": "Conception et évaluation d'un système léger de reconnaissance d'expressions faciales en temps réel",
        "bullets": [
          "Conception d'un CNN Mini-Xception personnalisé et très efficace (56 951 paramètres) à partir de zéro à l'aide de PyTorch pour classer sept émotions de base.",
          "Atténuation du grave déséquilibre de classes dans l'ensemble de données FERPlus à l'aide d'une stratégie optimisée de pondération des pertes à fréquence inverse de racine carrée, atteignant une précision de test de 75,40 %.",
          "Déploiement du modèle pour l'inférence de bord en temps réel à l'aide de MediaPipe BlazeFace, maintenant 30 FPS avec une latence ultra-faible (3,42 ms) sur le matériel CPU."
        ]
      }
    ],
    "projects": [
      {
        "title": "SENSATION : Système de navigation pour malvoyants",
        "context": "Séminaire de Master",
        "bullets": [
          "Conception d'un système d'assistance à la navigation fusionnant la segmentation sémantique DeepLabv3+ ResNet50 avec le routage GPS Valhalla pour un guidage sur les trottoirs en temps réel.",
          "Affinement du modèle sur l'ensemble de données Mapillary et exportation vers ONNX via TorchScript pour une inférence CPU/GPU efficace sur les flux de caméras en direct.",
          "Conception d'un algorithme d'analyse spatiale pour émettre des commandes directionnelles basées sur la distribution dominante des pixels du trottoir."
        ]
      },
      {
        "title": "Driver's Freund : chatbot multilingue IA",
        "context": "2025 – Présent",
        "bullets": [
          "Architecture d'un chatbot allemand full-stack pour le droit de la conduite à l'aide d'un pipeline de génération augmentée de récupération (MiniLM + Chroma + Perplexity).",
          "Implémentation d'un pipeline NLP bilingue (EN/DE) utilisant spaCy pour la classification et la génération, déployé sur un VPS avec Docker et automatisation CI/CD."
        ]
      },
      {
        "title": "Analyse des données sur la criminalité à Chicago",
        "context": "2024 – 2025",
        "bullets": [
          "Création d'un pipeline ETL de bout en bout corrélant les incidents criminels de Chicago avec les données météorologiques du département de police de Chicago et les API météorologiques.",
          "Déploiement de tests automatisés et de pipelines CI/CD via GitHub Actions pour garantir la reproductibilité complète du cycle de vie de l'ingénierie des données."
        ]
      }
    ],
    "publicationStatuses": [
      "Soumis · En cours d'examen",
      "Soumis · Préimpression en attente sur Research Square"
    ]
  },
  "es": {
    "banner": [
      "Graduado con un máster en Ciencia de Datos e investigador en IA aplicada, desarrollo sistemas inteligentes para el análisis de series temporales multivariantes, la detección de anomalías, RAG y visión por computador.",
      "Combino una investigación rigurosa en aprendizaje automático con ingeniería orientada a producción, transformando ideas innovadoras en soluciones escalables y explicables para retos científicos e industriales reales."
    ],
    "researchInterests": [
      "Aprendizaje automático",
      "IA explicable",
      "Detección de anomalías no supervisadas",
      "Recuperación-Generación Aumentada (RAG)",
      "Visión por computadora aplicada",
      "Inferencia de borde"
    ],
    "skillLabels": [
      "Aprendizaje profundo e IA",
      "Idiomas y backend",
      "Infraestructura y nube",
      "Visualización de datos y herramientas",
      "Idiomas hablados"
    ],
    "spokenLanguages": [
      "Inglés — C1 / Fluido",
      "Alemán — B1/B2 / Intermedio",
      "Bengalí — Nativo",
      "Noruego — Básico"
    ],
    "experiences": [
      {
        "role": "Científico de datos (estudiante trabajador)",
        "location": "Erlangen, Alemania",
        "duration": "Octubre de 2025 – marzo de 2026",
        "bullets": [
          "Desarrollé un microservicio Python de un extremo a otro para recuperar eventos de una API externa y publicarlos en Azure Event Hub como parte de una prueba de concepto.",
          "Habilité la integración del sistema multiagente con la plataforma EcoMAIN, colaborando con Alexander Thamm en la detección avanzada de anomalías.",
          "Mantuve y depuré aplicaciones frontend Vue.js, optimizando las llamadas API backend y alineando los componentes de la interfaz de usuario con requisitos técnicos complejos."
        ]
      },
      {
        "role": "Analista de datos (estudiante trabajador)",
        "location": "Erlangen, Alemania",
        "duration": "Dic. 2024 – septiembre 2025",
        "bullets": [
          "Gestioné bases de datos relacionales complejas (MS SQL, MySQL) en la división operativa de I+D, escribiendo consultas optimizadas para migraciones de datos extensas.",
          "Diseñé e implementé flujos de datos ETL/ELT automatizados, sincronizando datos de SharePoint y Excel a SQL usando Power Automate y Alteryx.",
          "Diseñé una nueva base de datos colaborativa de backend para datos de cartera y desarrollo para respaldar casos de uso digitales."
        ]
      },
      {
        "role": "Analista de datos",
        "location": "En remoto",
        "duration": "Octubre de 2021 – marzo de 2023",
        "bullets": [
          "Ejecuté procesos ETL complejos conectando Snowflake, MySQL y Excel para extraer y transformar conjuntos de datos a gran escala mediante Power Query.",
          "Creó paneles analíticos interactivos para proporcionar información procesable basada en datos a los ejecutivos interesados.",
          "Utilicé metodologías ágiles (Kanban, Scrum) para mapear los requisitos de las partes interesadas y agilizar la entrega del proyecto."
        ]
      }
    ],
    "education": [
      {
        "degree": "Maestría en Ciencias en Ciencia de Datos",
        "location": "Erlangen, Alemania",
        "duration": "Octubre de 2022 – junio de 2026",
        "thesisTitle": "Agente de detección de anomalías para datos de series temporales (Industria de Procesos) integrable en un Sistema Multiagente",
        "bullets": [
          "Diseñé un canal de aprendizaje automático no supervisado para detectar anomalías en datos de series de tiempo complejos y multivariados para la industria de procesos.",
          "Diseñó el sistema como un agente independiente y escalable para una integración perfecta en un ecosistema industrial de sistema multiagente más grande, completado en colaboración con Siemens Energy."
        ]
      },
      {
        "degree": "Licenciatura en Tecnología en Ciencias de la Computación e Ingeniería",
        "location": "Calcuta, India",
        "duration": "julio de 2017 – mayo de 2021",
        "thesisTitle": "Diseño y evaluación de un sistema liviano de reconocimiento de expresiones faciales en tiempo real",
        "bullets": [
          "Diseñé una CNN Mini-Xception personalizada y altamente eficiente (56,951 parámetros) desde cero usando PyTorch para clasificar siete emociones básicas.",
          "Se mitigó el desequilibrio de clases grave en el conjunto de datos de FERPlus mediante una estrategia optimizada de ponderación de pérdida de frecuencia inversa de raíz cuadrada, logrando una precisión de prueba del 75,40 %.",
          "Implementó el modelo para inferencia de borde en tiempo real utilizando MediaPipe BlazeFace, manteniendo 30 FPS con latencia ultrabaja (3,42 ms) en el hardware de la CPU."
        ]
      }
    ],
    "projects": [
      {
        "title": "SENSATION: Sistema de navegación para personas con discapacidad visual",
        "context": "Seminario de Maestría",
        "bullets": [
          "Diseñó un sistema de navegación asistida que fusiona la segmentación semántica DeepLabv3+ ResNet50 con el enrutamiento GPS Valhalla para orientación en aceras en tiempo real.",
          "Se ajustó el modelo en el conjunto de datos de Mapillary y se exportó a ONNX a través de TorchScript para una inferencia eficiente de CPU/GPU en transmisiones de cámaras en vivo.",
          "Diseñó un algoritmo de análisis espacial para emitir comandos direccionales basados en la distribución dominante de píxeles de la acera."
        ]
      },
      {
        "title": "Freund del conductor: Chatbot multilingüe con IA",
        "context": "2025 – Presente",
        "bullets": [
          "Diseñé un chatbot completo sobre derecho de conducción alemán utilizando un canal de generación aumentada de recuperación (MiniLM + Chroma + Perplexity).",
          "Implementé un pipeline de PNL bilingüe (EN/DE) usando spaCy para clasificación y generación, implementado en un VPS con Docker y automatización CI/CD."
        ]
      },
      {
        "title": "Análisis de datos sobre delitos en Chicago",
        "context": "2024 – 2025",
        "bullets": [
          "Construyó un canal ETL de extremo a extremo que correlaciona los incidentes criminales de Chicago con datos meteorológicos del Departamento de Policía de Chicago y API meteorológicas.",
          "Implementé pruebas automatizadas y canalizaciones de CI/CD a través de GitHub Actions para garantizar la reproducibilidad total del ciclo de vida de la ingeniería de datos."
        ]
      }
    ],
    "publicationStatuses": [
      "Enviado · En revisión",
      "Enviado · Preimpresión pendiente en Research Square"
    ]
  },
  "pl": {
    "banner": [
      "Absolwent studiów magisterskich z Data Science i badacz stosowanej sztucznej inteligencji, rozwijający inteligentne systemy do analizy wielowymiarowych szeregów czasowych, wykrywania anomalii, RAG i widzenia komputerowego.",
      "Łączę rzetelne badania nad uczeniem maszynowym z inżynierią produkcyjną, przekształcając nowe idee w skalowalne i wyjaśnialne rozwiązania rzeczywistych wyzwań naukowych i przemysłowych."
    ],
    "researchInterests": [
      "Uczenie maszynowe",
      "Wyjaśnialna sztuczna inteligencja",
      "Wykrywanie anomalii bez nadzoru",
      "Generacja wzmocniona odzyskiwaniem (RAG)",
      "Stosowane widzenie komputerowe",
      "Wnioskowanie krawędziowe"
    ],
    "skillLabels": [
      "Głębokie uczenie się i sztuczna inteligencja",
      "Języki i zaplecze",
      "Infrastruktura i chmura",
      "Wizualizacja danych i narzędzia",
      "Języki mówione"
    ],
    "spokenLanguages": [
      "Angielski — C1 / Biegły",
      "Niemiecki — B1/B2 / Średniozaawansowany",
      "Bengalski — rodzimy",
      "Norweski — podstawowy"
    ],
    "experiences": [
      {
        "role": "Analityk danych (pracujący student)",
        "location": "Erlangen, Niemcy",
        "duration": "Paź. 2025 – Marzec 2026",
        "bullets": [
          "Opracowano kompleksową mikrousługę języka Python do pobierania zdarzeń z zewnętrznego interfejsu API i publikowania ich w usłudze Azure Event Hub w ramach weryfikacji koncepcji.",
          "Umożliwiono integrację systemu wieloagentowego z platformą EcoMAIN, współpracując z Alexandrem Thammem przy zaawansowanym wykrywaniu anomalii.",
          "Utrzymywał i debugował aplikacje frontendowe Vue.js, optymalizując wywołania API backendu i dopasowując komponenty interfejsu użytkownika do złożonych wymagań technicznych."
        ]
      },
      {
        "role": "Analityk danych (pracujący student)",
        "location": "Erlangen, Niemcy",
        "duration": "grudzień 2024 – wrzesień 2025",
        "bullets": [
          "Zarządzał złożonymi relacyjnymi bazami danych (MS SQL, MySQL) w dziale operacyjnym R&D, pisząc zoptymalizowane zapytania dla rozbudowanych migracji danych.",
          "Zaprojektowano i wdrożono zautomatyzowane przepływy danych ETL/ELT, synchronizując dane z SharePoint i Excel do SQL przy użyciu Power Automate i Alteryx.",
          "Zaprojektował nową wspólną bazę danych zaplecza dla danych portfelowych i programistycznych w celu obsługi cyfrowych przypadków użycia."
        ]
      },
      {
        "role": "Analityk danych",
        "location": "Zdalnie",
        "duration": "Paź. 2021 – Marzec 2023",
        "bullets": [
          "Wykonywano złożone procesy ETL, łącząc Snowflake, MySQL i Excel w celu wyodrębniania i przekształcania dużych zbiorów danych za pomocą Power Query.",
          "Zbudowano interaktywne analityczne pulpity nawigacyjne, aby zapewnić zainteresowanym stronom kierowniczym przydatne i oparte na danych spostrzeżenia.",
          "Stosowane metodologie zwinne (Kanban, Scrum) w celu mapowania wymagań interesariuszy i usprawniania realizacji projektów."
        ]
      }
    ],
    "education": [
      {
        "degree": "Magister nauk o danych",
        "location": "Erlangen, Niemcy",
        "duration": "Paź. 2022 – Czerwiec 2026",
        "thesisTitle": "Agent do wykrywania anomalii dla danych szeregów czasowych (przemysł procesowy), który można zintegrować z systemem wieloagentowym",
        "bullets": [
          "Zaprojektował nienadzorowany potok uczenia maszynowego w celu wykrywania anomalii w złożonych, wielowymiarowych danych szeregów czasowych dla branży procesowej.",
          "Zaprojektowano system jako niezależny, skalowalny agent umożliwiający bezproblemową integrację z większym przemysłowym ekosystemem systemu wieloagentowego, ukończony we współpracy z firmą Siemens Energy."
        ]
      },
      {
        "degree": "Licencjat z informatyki i inżynierii",
        "location": "Kalkuta, Indie",
        "duration": "lipiec 2017 – maj 2021",
        "thesisTitle": "Projekt i ocena lekkiego systemu rozpoznawania wyrazu twarzy w czasie rzeczywistym",
        "bullets": [
          "Zaprojektował od podstaw niestandardowy, bardzo wydajny Mini-Xception CNN (56 951 parametrów), używając PyTorch do klasyfikacji siedmiu podstawowych emocji.",
          "Złagodzono poważną nierównowagę klas w zbiorze danych FERPlus przy użyciu zoptymalizowanej strategii ważenia strat w postaci pierwiastka kwadratowego z odwrotną częstotliwością, osiągając dokładność testu 75,40%.",
          "Wdrożono model wnioskowania brzegowego w czasie rzeczywistym przy użyciu MediaPipe BlazeFace, utrzymując 30 klatek na sekundę przy bardzo niskim opóźnieniu (3,42 ms) na sprzęcie procesora."
        ]
      }
    ],
    "projects": [
      {
        "title": "SENSATION: System Nawigacji dla Niewidomych",
        "context": "Seminarium Mistrzowskie",
        "bullets": [
          "Zaprojektowano system nawigacji wspomagającej, łączący segmentację semantyczną DeepLabv3+ ResNet50 z routingiem GPS Valhalla w celu zapewnienia wskazówek po chodniku w czasie rzeczywistym.",
          "Dopracowano model w zestawie danych Mapillary i wyeksportowano go do ONNX za pomocą TorchScript w celu wydajnego wnioskowania o CPU/GPU w przypadku strumieni z kamer na żywo.",
          "Opracowano algorytm analizy przestrzennej do wydawania poleceń kierunkowych w oparciu o dominujący rozkład pikseli chodnika."
        ]
      },
      {
        "title": "Przyjaciółka kierowcy: wielojęzyczny chatbot AI",
        "context": "2025 – obecnie",
        "bullets": [
          "Opracowano kompleksowy chatbot dotyczący niemieckiego prawa jazdy, wykorzystujący potok generacji rozszerzonej pobierania (MiniLM + Chroma + Perplexity).",
          "Wdrożono dwujęzyczny potok NLP (EN/DE) przy użyciu spaCy do klasyfikacji i generowania, wdrożony na VPS z Dockerem i automatyzacją CI/CD."
        ]
      },
      {
        "title": "Analiza danych dotyczących przestępczości w Chicago",
        "context": "2024 – 2025",
        "bullets": [
          "Zbudowano kompleksowy rurociąg ETL korelujący incydenty przestępcze w Chicago z danymi meteorologicznymi z Departamentu Policji w Chicago i interfejsami API dotyczącymi pogody.",
          "Wdrożono automatyczne testy i potoki CI/CD za pośrednictwem GitHub Actions, aby zapewnić pełną odtwarzalność cyklu życia inżynierii danych."
        ]
      }
    ],
    "publicationStatuses": [
      "Przesłano · W trakcie sprawdzania",
      "Przesłano · Przeddruk oczekuje na Placu Badawczym"
    ]
  },
  "cs": {
    "banner": [
      "Absolvent magisterského studia Data Science a výzkumník aplikované umělé inteligence, který vyvíjí inteligentní systémy pro analýzu vícerozměrných časových řad, detekci anomálií, RAG a počítačové vidění.",
      "Propojuji důkladný výzkum strojového učení s produkčním vývojem a převádím nové myšlenky do škálovatelných a vysvětlitelných řešení skutečných vědeckých a průmyslových výzev."
    ],
    "researchInterests": [
      "Strojové učení",
      "Vysvětlitelná AI",
      "Detekce anomálií bez dozoru",
      "Retrieval-Augmented Generation (RAG)",
      "Aplikované počítačové vidění",
      "Edge Inference"
    ],
    "skillLabels": [
      "Hluboké učení a umělá inteligence",
      "Jazyky a backend",
      "Infrastruktura a cloud",
      "Vizualizace dat a nástroje",
      "Mluvené jazyky"
    ],
    "spokenLanguages": [
      "Angličtina — C1 / Plynule",
      "Němčina — B1/B2 / středně pokročilí",
      "bengálština — domorodec",
      "Norština — základní"
    ],
    "experiences": [
      {
        "role": "Data Scientist (pracující student)",
        "location": "Erlangen, Německo",
        "duration": "Říjen 2025 – březen 2026",
        "bullets": [
          "Vyvinuli end-to-end mikroslužbu Pythonu pro načítání událostí z externího rozhraní API a jejich publikování do Azure Event Hub jako součást důkazu konceptu.",
          "Povolená integrace Multi-Agent System s platformou EcoMAIN ve spolupráci s Alexanderem Thammem na pokročilé detekci anomálií.",
          "Udržované a laděné frontendové aplikace Vue.js, optimalizace volání backendového API a sladění komponent uživatelského rozhraní se složitými technickými požadavky."
        ]
      },
      {
        "role": "Datový analytik (pracující student)",
        "location": "Erlangen, Německo",
        "duration": "Prosinec 2024 – září 2025",
        "bullets": [
          "Spravoval komplexní relační databáze (MS SQL, MySQL) v provozní divizi R&D, psaní optimalizovaných dotazů pro rozsáhlé migrace dat.",
          "Navrhl a implementoval automatizované datové toky ETL/ELT, synchronizoval data ze SharePointu a Excelu do SQL pomocí Power Automate a Alteryx.",
          "Vytvořila novou kolaborativní backendovou databázi pro portfolio a vývojová data pro podporu digitálních případů použití."
        ]
      },
      {
        "role": "Datový analytik",
        "location": "Na dálku",
        "duration": "Říjen 2021 – březen 2023",
        "bullets": [
          "Provádění komplexních procesů ETL propojením Snowflake, MySQL a Excelu pro extrahování a transformaci rozsáhlých datových sad pomocí Power Query.",
          "Vybudované interaktivní analytické řídicí panely, které poskytují výkonným zúčastněným stranám užitečné informace založené na datech.",
          "Použité agilní metodiky (Kanban, Scrum) ke zmapování požadavků stakeholderů a zefektivnění realizace projektů."
        ]
      }
    ],
    "education": [
      {
        "degree": "Master of Science v Data Science",
        "location": "Erlangen, Německo",
        "duration": "Říjen 2022 – červen 2026",
        "thesisTitle": "Detekce anomálií Agent pro data časových řad (Procesní průmysl), který lze integrovat do systému s více agenty",
        "bullets": [
          "Vytvořil kanál strojového učení bez dozoru pro detekci anomálií ve složitých, vícerozměrných datech časových řad pro zpracovatelský průmysl.",
          "Navrhli systém jako nezávislého, škálovatelného agenta pro bezproblémovou integraci do většího průmyslového ekosystému Multi-Agent System, dokončeného ve spolupráci se společností Siemens Energy."
        ]
      },
      {
        "degree": "Bakalář technologie v počítačové vědě a inženýrství",
        "location": "Kalkata, Indie",
        "duration": "červenec 2017 – květen 2021",
        "thesisTitle": "Návrh a vyhodnocení lehkého systému rozpoznávání výrazu obličeje v reálném čase",
        "bullets": [
          "Vytvořil vlastní, vysoce efektivní Mini-Xception CNN (56 951 parametrů) od nuly pomocí PyTorch ke klasifikaci sedmi základních emocí.",
          "Zmírnil závažnou nerovnováhu tříd v datové sadě FERPlus pomocí optimalizované strategie vážení inverzní ztráty frekvence s druhou odmocninou, čímž bylo dosaženo 75,40% přesnosti testu.",
          "Nasazený model pro odvozování hran v reálném čase pomocí MediaPipe BlazeFace, udržující 30 FPS s ultra nízkou latencí (3,42 ms) na hardwaru CPU."
        ]
      }
    ],
    "projects": [
      {
        "title": "SENSATION: Navigační systém pro zrakově postižené",
        "context": "Mistrovský seminář",
        "bullets": [
          "Navrhl asistenční navigační systém spojující sémantickou segmentaci DeepLabv3+ ResNet50 se směrováním GPS Valhalla pro navádění po chodníku v reálném čase.",
          "Doladili model na datové sadě Mapillary a exportovali jej do ONNX pomocí TorchScriptu pro efektivní vyvození CPU/GPU na živé přenosy z kamer.",
          "Vytvořil algoritmus prostorové analýzy pro vydávání směrových příkazů založených na dominantním rozložení pixelů chodníku."
        ]
      },
      {
        "title": "Driver's Freund: AI vícejazyčný chatbot",
        "context": "2025 – současnost",
        "bullets": [
          "Vytvořil full-stack chatbota německého řidičského práva pomocí kanálu Retrieval-Augmented Generation (MiniLM + Chroma + Perplexity).",
          "Implementován dvojjazyčný kanál NLP (EN/DE) využívající spaCy pro klasifikaci a generování, nasazený na VPS s automatizací Docker a CI/CD."
        ]
      },
      {
        "title": "Analýza dat o kriminalitě v Chicagu",
        "context": "2024–2025",
        "bullets": [
          "Vybudoval end-to-end ETL plynovod korelující chicagské zločiny s meteorologickými daty z chicagského policejního oddělení a meteorologickými API.",
          "Nasazené automatizované testování a kanály CI/CD prostřednictvím akcí GitHub, aby byla zajištěna plná reprodukovatelnost životního cyklu datového inženýrství."
        ]
      }
    ],
    "publicationStatuses": [
      "Odesláno · Probíhá kontrola",
      "Odesláno · Předtisk čeká na Research Square"
    ]
  },
  "pt": {
    "banner": [
      "Mestre em Ciência de Dados e investigador em IA aplicada, desenvolvo sistemas inteligentes para análise de séries temporais multivariadas, deteção de anomalias, RAG e visão computacional.",
      "Combino investigação rigorosa em aprendizagem automática com engenharia orientada para produção, transformando novas ideias em soluções escaláveis e explicáveis para desafios científicos e industriais reais."
    ],
    "researchInterests": [
      "Aprendizado de máquina",
      "IA explicável",
      "Detecção de anomalias não supervisionadas",
      "Geração Aumentada de Recuperação (RAG)",
      "Visão Computacional Aplicada",
      "Inferência de borda"
    ],
    "skillLabels": [
      "Aprendizado profundo e IA",
      "Idiomas e back-end",
      "Infraestrutura e nuvem",
      "Visualização de dados e ferramentas",
      "Idiomas falados"
    ],
    "spokenLanguages": [
      "Inglês – C1 / Fluente",
      "Alemão – B1/B2 / Intermediário",
      "Bengali – nativo",
      "Norueguês – Básico"
    ],
    "experiences": [
      {
        "role": "Cientista de Dados (estudante trabalhador)",
        "location": "Erlangen, Alemanha",
        "duration": "Outubro de 2025 – março de 2026",
        "bullets": [
          "Desenvolvi um microsserviço Python completo para recuperar eventos de uma API externa e publicá-los no Azure Event Hub como parte de uma prova de conceito.",
          "Habilitou a integração do sistema multiagente com a plataforma EcoMAIN, colaborando com Alexander Thamm na detecção avançada de anomalias.",
          "Mantive e depurei aplicativos frontend Vue.js, otimizando chamadas de API backend e alinhando componentes de UI com requisitos técnicos complexos."
        ]
      },
      {
        "role": "Analista de Dados (Estudante Trabalhador)",
        "location": "Erlangen, Alemanha",
        "duration": "Dez. 2024 – Setembro 2025",
        "bullets": [
          "Gerenciei bancos de dados relacionais complexos (MS SQL, MySQL) na divisão operacional de P&D, escrevendo consultas otimizadas para migrações extensas de dados.",
          "Projetei e implementei fluxos de dados ETL/ELT automatizados, sincronizando dados de SharePoint e Excel para SQL usando Power Automate e Alteryx.",
          "Arquitetei um novo banco de dados de back-end colaborativo para dados de portfólio e desenvolvimento para dar suporte a casos de uso digital."
        ]
      },
      {
        "role": "Analista de Dados",
        "location": "Remoto",
        "duration": "Outubro de 2021 – março de 2023",
        "bullets": [
          "Executei processos ETL complexos conectando Snowflake, MySQL e Excel para extrair e transformar conjuntos de dados em grande escala usando Power Query.",
          "Crie painéis analíticos interativos para fornecer insights acionáveis e baseados em dados às partes interessadas executivas.",
          "Utilizei metodologias ágeis (Kanban, Scrum) para mapear os requisitos das partes interessadas e agilizar a entrega do projeto."
        ]
      }
    ],
    "education": [
      {
        "degree": "Mestrado em Ciência de Dados",
        "location": "Erlangen, Alemanha",
        "duration": "Outubro de 2022 – junho de 2026",
        "thesisTitle": "Agente de detecção de anomalias para dados de séries temporais (Indústria de Processos) que pode ser integrado em um Sistema Multi Agente",
        "bullets": [
          "Arquitetei um pipeline de aprendizado de máquina não supervisionado para detectar anomalias em dados de séries temporais complexas e multivariadas para a indústria de processos.",
          "Projetou o sistema como um agente independente e escalável para integração perfeita em um ecossistema industrial maior de sistemas multiagentes, concluído em colaboração com a Siemens Energy."
        ]
      },
      {
        "degree": "Bacharel em Tecnologia em Ciência da Computação e Engenharia",
        "location": "Calcutá, Índia",
        "duration": "Julho de 2017 – maio de 2021",
        "thesisTitle": "Projeto e avaliação de um sistema leve de reconhecimento de expressão facial em tempo real",
        "bullets": [
          "Projetei um Mini-Xception CNN personalizado e altamente eficiente (56.951 parâmetros) do zero usando PyTorch para classificar sete emoções básicas.",
          "Mitigou o grave desequilíbrio de classe no conjunto de dados FERPlus usando uma estratégia otimizada de ponderação de perda de frequência inversa de raiz quadrada, alcançando 75,40% de precisão de teste.",
          "Implantei o modelo para inferência de borda em tempo real usando MediaPipe BlazeFace, sustentando 30 FPS com latência ultrabaixa (3,42 ms) no hardware da CPU."
        ]
      }
    ],
    "projects": [
      {
        "title": "SENSATION: Sistema de navegação para deficientes visuais",
        "context": "Seminário Mestre",
        "bullets": [
          "Projetamos um sistema de navegação assistiva que combina segmentação semântica DeepLabv3+ ResNet50 com roteamento GPS Valhalla para orientação na calçada em tempo real.",
          "Ajustou o modelo no conjunto de dados Mapillary e exportou-o para ONNX via TorchScript para inferência eficiente de CPU/GPU em streams de câmeras ao vivo.",
          "Projetei um algoritmo de análise espacial para emitir comandos direcionais com base na distribuição dominante de pixels da calçada."
        ]
      },
      {
        "title": "Driver's Freund: Chatbot multilíngue com IA",
        "context": "2025 – Presente",
        "bullets": [
          "Arquitetei um chatbot full-stack sobre direito de trânsito alemão usando um pipeline de geração aumentada de recuperação (MiniLM + Chroma + Perplexity).",
          "Implementei um pipeline de PNL bilíngue (EN/DE) utilizando spaCy para classificação e geração, implantado em um VPS com Docker e automação CI/CD."
        ]
      },
      {
        "title": "Análise de dados criminais de Chicago",
        "context": "2024 – 2025",
        "bullets": [
          "Construiu um pipeline ETL de ponta a ponta correlacionando incidentes criminais de Chicago com dados meteorológicos do Departamento de Polícia de Chicago e APIs meteorológicas.",
          "Implantei testes automatizados e pipelines de CI/CD por meio do GitHub Actions para garantir total reprodutibilidade do ciclo de vida da engenharia de dados."
        ]
      }
    ],
    "publicationStatuses": [
      "Enviado · Em revisão",
      "Enviado · Pré-impressão pendente na Research Square"
    ]
  }
} as const;
